# Generated by Django 4.0.1 on 2024-03-15 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0002_team_player_alter_bet_best_allrounder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='best_allrounder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='best_allrounder', to='betting.player'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='best_batsman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='best_batsman', to='betting.player'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='best_bowler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='best_bowler', to='betting.player'),
        ),
    ]
