# Generated by Django 4.0.1 on 2024-03-16 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0003_alter_bet_best_allrounder_alter_bet_best_batsman_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='best_allrounder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_best_allrounder', to='betting.player'),
        ),
        migrations.AddField(
            model_name='match',
            name='best_batsman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_best_batsman', to='betting.player'),
        ),
        migrations.AddField(
            model_name='match',
            name='best_bowler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_best_bowler', to='betting.player'),
        ),
        migrations.AddField(
            model_name='match',
            name='winning_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='betting.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='betting.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='betting.team'),
        ),
    ]
