# Generated by Django 4.0.1 on 2024-03-16 13:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('betting', '0004_match_best_allrounder_match_best_batsman_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bet',
            unique_together={('user', 'match')},
        ),
    ]
